{{ if .Values.application.istio.enableByYaml }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.application.istio.namespace }}
  labels:
    istio-injection: {{ .Values.application.istio.isolation }}
{{ end }}