apiVersion: v1
data:
{{ if .Values.application.pullSecret.secretIsBase64 }}
  .dockerconfigjson: {{ .Values.application.pullSecret.dockerconfig }}
{{ else }}
  .dockerconfigjson: {{ .Values.application.pullSecret.dockerconfig | b64enc }}
{{ end }}
kind: Secret
metadata:
  name:  {{ .Values.application.pullSecret.name  | default "pull-secret" }} 
type: kubernetes.io/dockerconfigjson
